# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Tale Nguyen
paginate:       5
baseurl:        ""
url:            "https://talenguyen.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Giang Nguyen
  url:          http://talenguyen.github.io
  email:        giangnguyen.tale@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
