excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://talenguyen.github.io
title: "Build Future by Code"
tagline: "Code for Fun"
email: giangnguyen.tale@gmail.com
author: Nguyen Truong Giang
description: "My name is Nguyen Truong Giang, and I'm software engineer (mainly Android) and contributor of some open source projects. This is my personal blog where I publish technical articles about android, software architecture, user interfaces and user experience. I’m a sports enthusiast. I love football (don’t call it soccer!!!)."
paginate: 3
google_analytics: 123
