excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://talenguyen.github.io
title: Awesome
email: giangnguyen.tale@gmail.com
author: Nguyen Truong Giang
description: My awesome new site
paginate: 3
google_analytics: 123